### ISSUE TITLE
Prevent duplicate rel creation

### ISSUE THREAD

**Issue by subvertallchris** [graphaware/neo4j-timetree#13]
I use TimeTree immediately after a Cypher `MERGE`, so it sometimes ends in a new node, sometimes does not. I need to connect these maybe-new-maybe-not nodes to the time tree, but only if the relationship does not already exist. For now, I'm forced to perform an extra query to figure out if this should happen, but it would be really nice if this logic could be handled within the plugin. Is that doable?

**Comment by bachmanm** [comment]
fixed in master, will release with the next version, thank for spotting this!

**Comment by subvertallchris** [comment]
This is fantastic, thank you!
