### ISSUE TITLE
Support batched transactions

### ISSUE THREAD

**Issue by apshoemaker** [graphaware/neo4j-timetree#18]
We are planning to use this when we do large data imports (>1M nodes).  In order to facilitate speedy imports, I am batching the transactions approximately 20k at a time - which means that I am taking finite control over 
the transaction idiom (rather than using try-with-resources):

It seems that internally, you are using the java 7 idiom as follows SingleTimeTree.java:110:
```
    /**
     * {@inheritDoc}
     */
    @Override
    public Node getOrCreateInstant(TimeInstant timeInstant) {
        Node instant;

        try (Transaction tx = database.beginTx()) {
            DateTime dateTime = new DateTime(timeInstant.getTime(), timeInstant.getTimezone());

            Node timeRoot = getTimeRoot();
            tx.acquireWriteLock(timeRoot);
            instant = getOrCreateInstant(timeRoot, dateTime, timeInstant.getResolution());

            tx.success();
        }

        return instant;
    }
```

By doing it this way, it greatly slows down the speed of imports.  Would there be a way to support batched transactions for faster performance?  My cursory glance at SingleTimeTree.java:277 makes me wonder if making this method public:
```
private Node getOrCreateInstant(Node parent, DateTime dateTime, Resolution targetResolution)
```

As well as this method at SingletimeTree.java:145:
```
    protected Node getTimeRoot()
```
would give me the finite control I need.  I haven't gone through your project 100% just yet, so making these methods public could be potentially very dangerous (particularly getTimeRoot, I think).  If there is a better or different way, please let me know what you think.

**Comment by bachmanm** [comment]
If you manage transactions yourself in Java, any nested transaction (including the one TimeTree creates) is just a placebo transaction, meaning that it has no effect. So you can already do what you're talking about with the current version of the library. Just don't worry about the transactions.

Once thing I would say, before implementing batching yourself, is have a look at this: https://github.com/graphaware/neo4j-framework/tree/master/tx-executor and especially https://github.com/graphaware/neo4j-framework/blob/master/tx-executor/src/main/java/com/graphaware/tx/executor/batch/IterableInputBatchTransactionExecutor.java

**Comment by apshoemaker** [comment]
Thank you for getting back so fast!

Thank you also for the great information.  My assumptions must have been incorrect and the slowdown attributed to the extra nodes being created during the transaction (I should qualify "slow down" as small, but noticeable and acceptable understanding how it actually works, now).  I did not realize that nested transactions had no overall effect.

I will take a look at your batch transaction executor.  Thanks again for the info!
