### ISSUE TITLE
insufficient Time Root exists check

### ISSUE THREAD

**Issue by anragab** [graphaware/neo4j-timetree#20]
The getTimeRoot() check doesn't ensure that the timeTreeRoot was committed. Hence if the first transaction was not committed. The application always throws an exception that the time root doesn't exist.

    protected Node getTimeRoot() {
        if (timeTreeRoot != null) {
            return timeTreeRoot;
        }
        ....
    }

Suggestion for improvement:

    protected Node getTimeRoot() {
        try { timeTreeRoot.getDegree() } catch(Exception e) { timeTreeRoot = null; }

        if (timeTreeRoot != null) {
            return timeTreeRoot;
        }
        ....
    }

Safer way to manage root:

	protected synchronized Node getTimeRoot() {
		try {
			if (timeTreeRoot == null)
				throw new NotFoundException();
			timeTreeRoot.getDegree();
		} catch (NotFoundException e) {
			try (ResourceIterator<Node> roots = db.findNodes(TimeTreeRoot)) {
				Node root = roots.next();
				if (roots.hasNext())
					throw new IllegalStateException("multiple time roots found!");
				timeTreeRoot = root;
			} catch (NoSuchElementException e1) {
				timeTreeRoot = database.createNode(TimeTreeRoot);
			}
		}

		return timeTreeRoot;
	}

**Comment by bachmanm** [comment]
well spotted, thanks! Fixed in next release (today)
