### ISSUE TITLE
Request: method to get events using a List of relationship types

### ISSUE THREAD

**Issue by subvertallchris** [graphaware/neo4j-timetree#21]
Something like:

```
List<Event> getEvents(TimeInstant startTime, TimeInstant endTime, List<RelationshipType> relationshipTypes);
```

Then the web APIs could be modified to accept a param that is a list of relationship types instead of a single type.

What do you think? I can try my hand at a PR if you're into it.

**Comment by bachmanm** [comment]
Good idea, PRs are welcome! Otherwise I'll try to do it for next release, shouldn't take too long at all. Cheers!

**Comment by subvertallchris** [comment]
Awesome. I'd like to give it a try, if that's alright. I'll see if I can work on it tonight or tomorrow.
