### ISSUE TITLE
How to define multiple nodes for auto attachment in neo4j.properties

### ISSUE THREAD

**Issue by jeremykendall** [graphaware/neo4j-timetree#24]
It's clear how to specify a single label for automatically attaching events to the TimeTree in `neo4j.properties`. I've followed those instructions and had success.

```
# Nodes which represent events and should be attached automatically have to be defined
com.graphaware.module.TT.event=hasLabel('Email')
```

What's not clear is how to specify multiple labels for automatic attachment in `neo4j.properties`. Could you provide an example?

(I did review the [Inclusion Policies](https://github.com/graphaware/neo4j-framework/tree/master/common#inclusion-policies) documentation, but it still wasn't clear to me how to accomplish this in `neo4j.properties`.)

**Comment by bachmanm** [comment]
Hi Jeremy, I agree this is not super-clear, so I'll leave the issue open until we fix the docs, for now:

`hasLabel('Email') || hasLabel('AnotherLabel')`

**Comment by jeremykendall** [comment]
Works like a champ. Thanks!

**Comment by bachmanm** [comment]
updated readme

**Comment by jeremykendall** [comment]
Awesome! Thanks again for your help.
