### ISSUE TITLE
Feature Request: Auto-Attach working with multiple TT roots

### ISSUE THREAD

**Issue by ikwattro** [graphaware/neo4j-timetree#26]
It would be nice to be able to use auto-attach with multiple TimeTree Roots.

Proposed solution : 

* new Configuration option `com.graphaware.module.TT.rootNode=rootNodeID`
* each event node would need to have this rootNodeID property for the `beforeCommit` logic to work properly

**Comment by bachmanm** [comment]
fixed and tested, released in a few mins in version 2.2.2.31.22
