### ISSUE TITLE
TimeTree Rebuilding Itself even w/o config changes

### ISSUE THREAD

**Issue by bachmanm** [graphaware/neo4j-timetree#28]
When the database restarts, timetree shouldn't be rebuilt if the config hasn't changed. @ikwattro will provide an example of when that isn't true.

**Comment by ikwattro** [comment]
Here a gist with the output of the `console.log` file and my `neo4j.properties` file content.

https://gist.github.com/ikwattro/ddbc74595d2fd12819d0

Please note that it has the same behavior with only one TT module defined in the configuration

**Comment by bachmanm** [comment]
fix will be released very soon (today or tomorrow)

**Comment by ikwattro** [comment]
:+1:
