### ISSUE TITLE
Allow possibility to create "intermediate time nodes" in NEXT chain

### ISSUE THREAD

**Issue by ikwattro** [graphaware/neo4j-timetree#30]
With the current implementation, days that are not connected to events are not created. So it makes for e.g. the possibility to do time queries by matching the length of the multiple NEXT relationships between two days impossible.

Would it be possible to make this configurable, so `createIntermediateTimeNodes=true` for e.g. ?

**Comment by bachmanm** [comment]
The TimeTree has always been meant to be sparse. Is this still a feature you need? Couldn't you subtract the timestamps of the events attached to the tree to find the time difference? Or was there another use case that you can't implement with the TimeTree as it is now? Cheers!

**Comment by ikwattro** [comment]
I don't **need** it, and I don't see other use cases right now. I understand the **sparse** problem when using resolutions like minute or seconds.
