### ISSUE TITLE
FR: Configurable relationship direction between timeNode and event

### ISSUE THREAD

**Issue by ikwattro** [graphaware/neo4j-timetree#31]
This is a **Feature Request**

Why ?

Take the following graph : 

```
(user)-[:LAST_EVENT]->(event)-[:PREV_EVENT]->(event)
(event)-[:OPENED_PR]->(pullRequest)-[:ON_REPO]->(repository)
(event)-[:AT_TIME]->(minute)
```

Let's say I want to find people having worked on the same repositories than me (so here the `OPENED_PR` rel type can also be `OPENED_ISSUE`, `CLOSED_PR`, etc..), I can not traverse the graph in "blind" (so with no relationship type defined) without traversing the time tree too or if I go in "blind" it has several performance impact on the queries.

The current implementation of the plugin forces me to define all possible relationship types from the event node in order to avoid to traverse the TT.

**Comment by bachmanm** [comment]
Will be released with 2.2.4.34.24
