### ISSUE TITLE
Avoid getAllNodes in initialize when inclusion policies contains hasLabel

### ISSUE THREAD

**Issue by ikwattro** [graphaware/neo4j-timetree#35]
When in the configuration, we define an InclusionPolicy of `hasLabel` for `com.graphaware.module.ID.event`, there is no need to get **ALL** nodes of the db. We can just find nodes by the labels defined by the Inclusion policy.

https://github.com/graphaware/neo4j-timetree/blob/master/src/main/java/com/graphaware/module/timetree/module/TimeTreeModule.java#L101

This might reduce the initialize process on config change by a certain time.

However, I didn't find any method in `NodeInclusionPolicy` to retrieve the possible labels defined.

**Comment by bachmanm** [comment]
Framework ready for this, TimeTree will be fixed with next release

**Comment by ikwattro** [comment]
awesome !

**Comment by bachmanm** [comment]
You can now define your own InclusionPolicy, e.g.:

```java
package com.graphaware.module.timetree.module;

import com.graphaware.common.policy.BaseNodeInclusionPolicy;
import org.neo4j.graphdb.DynamicLabel;
import org.neo4j.graphdb.GraphDatabaseService;
import org.neo4j.graphdb.Label;
import org.neo4j.graphdb.Node;
import org.neo4j.helpers.collection.Iterables;

public final class IncludeEvents extends BaseNodeInclusionPolicy {

    private static final Label EVENT = DynamicLabel.label("Event");

    private static final IncludeEvents INSTANCE = new IncludeEvents();

    public static IncludeEvents getInstance() {
        return INSTANCE;
    }

    private IncludeEvents() {
    }

    @Override
    public boolean include(Node node) {
        return node.hasLabel(EVENT);
    }

    @Override
    protected Iterable<Node> doGetAll(GraphDatabaseService database) {
        return Iterables.asResourceIterable(database.findNodes(EVENT));
    }
}
```

Then you can use it in neo4j-properties like this:

```
com.graphaware.module.TT.event=com.graphaware.module.timetree.module.IncludeEvents
```
