### ISSUE TITLE
Configuration is not read from neo4j properties file

### ISSUE THREAD

**Issue by moshebeeri** [graphaware/neo4j-timetree#39]
I am getting default time tree configuration,
Using latest, neo4j, graphaware framework, and neo4j-timetree.
http://localhost:7474/graphaware/timetree/now works, but it not using my configuration (1 second, and costume root name). so I get this time tree

![screen shot 2015-08-06 at 3 26 12 pm](https://cloud.githubusercontent.com/assets/574405/9111403/91214eaa-3c4f-11e5-8633-01fd18df083a.png)

any advice if you can please :+1:

**Comment by bachmanm** [comment]
The configuration is only applicable to automatic event attachment. For what you are doing (i.e. manual API calls), you need to issue a `GET http://localhost:7474/graphaware/timetree/{rootNodeId}/now?resolution=second`

**Comment by moshebeeri** [comment]
Thanks, but the automatic mode is not working for some reason. 
I concluded its since the configuration is not read.
this is what my neo4j properties file looks like 
![screen shot 2015-08-06 at 3 44 52 pm](https://cloud.githubusercontent.com/assets/574405/9111695/21313b2a-3c52-11e5-8a10-fc7c77a0cba7.png)

**Comment by bachmanm** [comment]
What's not working? Could you pls elaborate? What does the request / query that you're executing look like?

**Comment by moshebeeri** [comment]
Thanks for the reply, sure I can, I expected the new event new I have created would automatically attache to the time tree node and if not exist it would be created.
That not happened when I added the new event, so I am missing something (though I read the documentation four times).
Does the automatic mode do what I think it should? and what should I do in order to make it work?

**Comment by bachmanm** [comment]
Could you please stop opening other issues for the same thing and focus on this one? Again, could you please provide the Cypher query you used for creating the event?
