### ISSUE TITLE
Automatic Event Attachment (multiple props) does not seem to work

### ISSUE THREAD

**Issue by Ivy2012** [graphaware/neo4j-timetree#45]
Hi,

Running neo4j 2.2.2.
I'm trying to auto-attach with the following settings:
```
com.graphaware.runtime.enabled=true
com.graphaware.module.TT.1=com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper
com.graphaware.module.TT.event=hasProperty('timestamp') || hasProperty('mytimestamp')
com.graphaware.module.TT.autoAttach=true
```

For created nodes like this, automatic attachment works fine:
```
create (n:MyNode { timestamp: 1444632997000 }) return n;
```

However, if I try the same for a new node with the property "mytimestamp", it fails:
```
create (n:MyNode { mytimestamp: 1444632997000 }) return n;
```

Please collaborate.
Is my boolean expression for the .event property not correct?

**EDIT**: I see what's wrong here now. ".event" only defines which nodes will qualify, and not which properties are the timestamps. Sorry for asking too quick. 
But this leads me to the new question: can I work with multiple "timestamp properties" on nodes?
F.e. can I auto-attach both timestamps in the following node to the TimeTree? Or better: **what is best practice for working with ranges**?
```
create (n:MyNode {
timestamp_from: 1444531887000,
timestamp_to: 1444632997000
}) return n;
```

**Comment by ikwattro** [comment]
You can define 2 TimeTree modules, one for each property : 

```
com.graphaware.runtime.enabled=true
com.graphaware.module.TT.1=com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper
com.graphaware.module.TT.event=hasLabel('MyNode')
com.graphaware.module.TT.autoAttach=true
com.graphaware.module.TT.timestamp=timestamp_from
com.graphaware.module.TT.relationship=FROM_TIME

com.graphaware.module.TS.2=com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper
com.graphaware.module.TS.event=hasLabel('MyNode')
com.graphaware.module.TS.autoAttach=true
com.graphaware.module.TS.timestamp=timestamp_to
com.graphaware.module.TS.relationship=TO_TIME
```

**Comment by Ivy2012** [comment]
@ikwattro Thanks a lot! I was not aware of this. Excellent solution.
