### ISSUE TITLE
Change GET to POST

### ISSUE THREAD

**Issue by ikwattro** [graphaware/neo4j-timetree#47]
For the API endpoints where the result is affecting the state of the database, I think it would make sense to change the HTTP methods to POST.

In a worst scenario, if a user has url locations to the plugin in his source code (think of Javascript for eg) and the state of nowaydays robots (Google can evaluate Javascript now), if the user's database can be crawled by such robots, they might be creating new TT nodes on every crawl.

This was the worst case, the overall case is that `GET` requests should be `SAFE`

**Comment by bachmanm** [comment]
fairy nuff!
