### ISSUE TITLE
Prevent retrospectice initialization when auto-attach is enabled.

### ISSUE THREAD

**Issue by phamann** [graphaware/neo4j-timetree#48]
Hello,

We are having an issue installing the TimeTree plugin in our production environment. This seems to be due to the fact that the initialisation process retrospectively goes and attaches the tree to all pre-existing event nodes we have defined in `com.graphaware.module.TT.event=hasLabel('Event')` property. We have DB with 1M+ nodes and therefore this takes an extremely long time, eventually causing us to kill the JVM process to restore traffic.

Is there a way to disable this behaviour on startup, i.e. still have auto-attach enabled but only for new Nodes created post startup, and not running the initialization.  Perhaps in relation to the [`initializeUntil`](https://github.com/graphaware/neo4j-timetree/blob/master/src/main/java/com/graphaware/module/timetree/module/TimeTreeConfiguration.java#L67) configuration?

Thanks in advance for your help.

**Comment by bachmanm** [comment]
Hi, indeed, if you're using the latest version of the Framework (2.1.3.37) and TimeTree (2.1.3.37.24), you should be able to set
```
com.graphaware.module.TT.initializeUntil=0
```

which will prevent this behaviour. I would be interested though in why it's killing your database, 1M+ nodes should not take such a long time. I'm assuming you can't share your DB, but we'll try to write a perf test around this, because it should work.

Cheers!

**Comment by bachmanm** [comment]
It's actually crawling the entire database, because I can't look at all the nodes by label, due to https://github.com/neo4j/neo4j/issues/6087. I guess we'll have to wait for a fix.

**Comment by phamann** [comment]
Hi @bachmanm thank you for your speedy response.

The versions we are using are:
- *35* for the framework: `graphaware-server-community-all-2.2.5.35`
- *24* for the TimeTree plugin: `graphaware-timetree-2.2.5.35.24`
Would the `initializeUntil=0` config still work with this version combination? Or will we need to upgrade our version of NEo to > `2.2.5`?

Sadly, I can't share the DB with you. But it seems as per yourt second comment that may be causing the perf issues. I have also noticed at our `(:Event)` nodes are not indexed which wouldn't have helped the situation.

**Comment by bachmanm** [comment]
I'm afraid that's not gonna work in 2.2.5.35. One way I can think of is to make the Framework think that the module has been running against that database previously. That's tricky. Have a look at `GraphPropertiesMetadataRepository#persistModuleMetadata`. That's one option. The other option is to fork the repo, checkout the 2.2.5.35 tag, and just disable the initialisation. The third option is that we can do one of the things above for you as consultancy, in which case please get in touch by email (info (at) graphaware (dot) com. Else you'll have to upgrade to 2.3.1... :|

**Comment by phamann** [comment]
Ok, we will investigate what is required to upgrade our instance to Neo `2.3.1` as that would be more suitable in the long run than hacking around the plugin. Once again thank you for your help.
