### ISSUE TITLE
autoattach not working

### ISSUE THREAD

**Issue by nrgjack** [graphaware/neo4j-timetree#49]
Hi, 

i'm using graphaware timetree and uuid plugin 

versions: 
- neo4j-community_windows-x64_2_3_2.exe
- graphaware-server-community-all-2.3.2.37.jar
- graphaware-uuid-2.3.2.37.8.jar
- graphaware-timetree-2.3.2.37.24.jar

i manage to create date/time node with the api, 

now i'm trying to enable autoattach at first on every node but it's not working

i have this configuration

```

com.graphaware.runtime.enabled=true
com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper
com.graphaware.module.TT.1=com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper
com.graphaware.module.TT.autoAttach=true
```

am i misconfiguring something ?

**Comment by jotomo** [comment]
According to https://github.com/graphaware/neo4j-timetree#automatic-event-attachment your need to define another setting:
```
# Nodes which represent events and should be attached automatically have to be defined
com.graphaware.module.TT.event=hasLabel('Email')
```
The link explains possible settings further.

**Comment by luanne** [comment]
By default, only nodes with label `Event` are auto-attached to the timetree. As @jotomo points out, you can override this.
Also, the property that represents the time in ms is `timestamp`. This again, can be overridden-

```
# Optionally, a property on the event nodes that represents the the time (long) at which the event took place must be specified (defaults to "timestamp")
com.graphaware.module.TT.timestamp=time
```

**Comment by bachmanm** [comment]
I'd also add that you need to install Neo4j from a .zip or .tar.gz, not using the .exe / .dmg installer. Please report back if you got it working

**Comment by nrgjack** [comment]
thank you for your replies

i thought both timestamp and event were optional,
i tried to add thiese configuration too but with no success. 

i've read bachmanm suggestion to use the zip file also in a very old topic
i hoped that the last version not having this issue. 

i will try the zip version by the way

thanks for now

**Comment by nrgjack** [comment]
i tried also with the zip version with the same result. 

- neo4j-community-2.3.2-windows.zip

same plugins as before

i tried also as administrator

graphaware time tree api is working as expected, uuid is working too.

the only thing that is not working is autoattach...

my neo4j.properties
`com.graphaware.runtime.enabled=true
com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper
com.graphaware.module.TT.1=com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper
com.graphaware.module.TT.autoAttach=true
com.graphaware.module.TT.event=hasLabel('Test')
`

i tried creating a Test node but no timetree created and no autoattach.

i tried also deleting 
`com.graphaware.module.TT.event=hasLabel('Test')`
and i tried creating an Event node but again no autoattach.

maybe neo4j for windows is not compatible with autoattach ?

thanks again for your time 

Jack

**Comment by luanne** [comment]
@nrgjack do you have a `timestamp` property on the node you created? And is the value a `long` representation of the time in ms?

**Comment by nrgjack** [comment]
no

**Comment by luanne** [comment]
Then that's it- the node to be auto attached to the timetree requires a property that represents the timestamp (in milliseconds). By default, this property is `timestamp`. 
You can change this via configuration-

```
# Optionally, a property on the event nodes that represents the the time (long) at which the event took place must be specified (defaults to "timestamp")
com.graphaware.module.TT.timestamp=time
```
For example, the above would indicate that the property on your event node is called `time` and it contains the time in milliseconds.

**Comment by nrgjack** [comment]
than you very much, 

my mistake was to have nodes without any kind of property,

i misunderstood the word optionally 

now it is working both on the .exe and the .zip neo4j

**Comment by jotomo** [comment]
Hm, the _optionally_ prefix can indeed be misleading. It's optional to _configure_ the setting, but the setting must have a value and the constraint specified must be met. Having the default specified (in parenthesis at the end) clarifies that the setting doesn't have to be set. Also, someone reading this the first time might skip entries starting with _optionally_, assuming it's not mandatory, thereby missing the constraints specified in the comments (a _timestamp_ property being mandatory unless otherwise configured, a mandatory _Event_ label ...). In short: it's easy to confuse which graph constraints are mandatory and which configuration settings are mandatory. I think that's exactly what lead to the confusion here.

**Comment by luanne** [comment]
I'll update the docs to clearly list what is expected of nodes to be auto-attached to the timetree, it's true that nothing really says this. Thanks for the comments!
