### ISSUE TITLE
Feature request: Why can't we add properties to AT_TIME relationship.

### ISSUE THREAD

**Issue by sreekanthb** [graphaware/neo4j-timetree#51]
Something like.
ttRelationProp="key/val"
It becomes easy to specify/identify at what event the node is connected to TT nodes.

**Comment by bachmanm** [comment]
what's the use case? Why can't the properties be on the event node? Thx

**Comment by sreekanthb** [comment]
A person changes his state from one(active) to another(inactive) alternatively and want to calculate the time between those states and total time he spent between the states in a particular day.
I can use config to create different relationships for each state and query the path from a particular day to person node and calculate.
It will be convenient if there is a way to add dynamic states[AT_TIME {state: active}/AT_TIME {state:inactive}] using relationship props. TT module can be extended to any type of relationship without changing the configuration.
I hope this use case makes it clear. Thanks.

**Comment by bachmanm** [comment]
Could you maybe register 2 different trees - one that would attach events with `BECAME_ACTIVE_AT_TIME`, and another one with `BECAME_INACTIVE_AT_TIME`?

**Comment by bachmanm** [comment]
closing as there is a workaround
