### ISSUE TITLE
Mention that a configuration value in neo4j.conf is required

### ISSUE THREAD

**Issue by spacecowboy** [graphaware/neo4j-timetree#58]
The REST calls are not available unless 

```
dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware
```

is specified in `neo4j.conf`. The README should mention this to avoid confusion, like here:
https://github.com/neo4j/docker-neo4j/issues/36#issuecomment-226107181

**Comment by bachmanm** [comment]
fixed
