### ISSUE TITLE
Unable to create time instant of historical dates

### ISSUE THREAD

**Issue by kknehra** [graphaware/neo4j-timetree#61]
Epochs such as 894409200 do not seem to be initialising.

I am using the following code (with objects in place of types) to get the show on the road.

`TimeTreeBackedEvents.attachEvent(Node, RelationshipType, TimeInstant.instant(epochs)`

I haven't found an exact time but it looks like dates before 2000 and maybe even 2001 seem to be initialised as having 0 epochs.

The same code with epoch: 1472206009, works just fine and creates a new time instant in the tree.

**Comment by ikwattro** [comment]
Hi @kknehra 

time instants in this library are expressed in milliseconds (long). Can you try with `894409200000` and report if your issue is fixed.

**Comment by kknehra** [comment]
Hi @ikwattro 

Many thanks for your reply. My mistake, I didn't carefully enough read the parameter constraints.

I solved this using the following:

`Date.toInstant().getEpochSecond() * 1000`

This converted my time in seconds to milliseconds which is what was causing the issue.

Kind regards.

**Comment by ikwattro** [comment]
No worries, In java 8 you can also use `ZonedDateTime.now().toInstant().toEpochMilli();`
