### ISSUE TITLE
Timestamp for relationships itself

### ISSUE THREAD

**Issue by pito-svk** [graphaware/neo4j-timetree#65]
It's possible for relationships itself to assign timestamp? Or is there a better solution?

For example user creates post:

```(user:User)-[:CREATED {timestamp}]->(post:Post)```

Or  user likes existing post to know when that happened:

```(user:User)-[:LIKED {timestamp}]->(post:Post)```

For first case attaching timestamp would be ok to assign it to a post node, but in the second case I am not creating new node, just assign relationship of existing nodes.

Thanks!

**Comment by ikwattro** [comment]
@pito-svk How do you expect relationships to be attached to the timetree ?

Basically what you are describing is events so you would have `Event` nodes containing the timestamp and being attached to the timetree. Depending on your queries this is not always a good solution, so best write down what your requirements are.

If you don't need a timetree, you can easily add the timestamp yourself during your create queries : 

```
MATCH (u:User {id: 1})
CREATE (p:Post {id: 123, title: "Super Post"})
CREATE (u)-[:CREATE {timestamp: timestamp()}]->(p)
```
