### ISSUE TITLE
ga.* procedures not visible 

### ISSUE THREAD

**Issue by joelstevick** [graphaware/neo4j-timetree#66]
I am not seeing any procedures (ga.*) in results for "call dbms.procedures()"

My environment:
1. Ubuntu 16.04.2 LTS
2. Neo4j EE 3.0.7
3. GraphAware plugins: graphaware-server-community-all-3.0.7.44.jar, graphaware-timetree-3.0.7.44.26.jar

I added com.graphaware.runtime.enabled=true to neo4j.conf

I restarted the neo4j server

neo4j.log reports "GraphAware started."

Any help you can give me would be greatly appreciated.

Thanks,
Joel

**Comment by omarlarus** [comment]
Hi @joelstevick !
To enable the time-tree module you need to put a properly configuration in your neo4j.conf file.
You can find an example [here](https://github.com/graphaware/neo4j-timetree#automatic-event-attachment).
As you can see you need to declare the Bootstrapper (TimeTreeModuleBootstrapper) to allow the module to run. 

Omar
