### ISSUE TITLE
Auto-attach does not attach

### ISSUE THREAD

**Issue by valandir** [graphaware/neo4j-timetree#72]
I have two TimeTree auto attach routines along with the UUID module configured as follows:
```
#*****************************************************************
# GraphAware UUID Config
#*****************************************************************

com.graphaware.runtime.enabled=true

#UIDM becomes the module ID:
com.graphaware.module.UIDM.1=com.graphaware.module.uuid.UuidBootstrapper

#optional, default is uuid:
com.graphaware.module.UIDM.uuidProperty=uuid

#optional, default is false:
com.graphaware.module.UIDM.stripHyphens=false


#optional, default is uuidIndex
com.graphaware.module.UIDM.uuidIndex=uuidIndex

#optional, default is uuidRelIndex
com.graphaware.module.UIDM.uuidRelationshipIndex=uuidRelIndex


#*****************************************************************
# GraphAware Timetree Auto attach Config
#*****************************************************************

com.graphaware.module.TT.2=com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper
com.graphaware.module.TT.event=hasLabel('Fault')
com.graphaware.module.TT.relationship=faultStarted
com.graphaware.module.TT.autoAttach=true
com.graphaware.module.TT.timestamp=dateOpened
com.graphaware.module.TT.resolution=MINUTE

com.graphaware.module.TS.3=com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper
com.graphaware.module.TS.event=hasLabel('Fault')
com.graphaware.module.TS.relationship=faultEnded
com.graphaware.module.TS.autoAttach=true
com.graphaware.module.TS.timestamp=dateClosed
com.graphaware.module.TS.resolution=MINUTE
```
When I create a Fault node using the web based interface with neo4j it creates the time tree attachments no problem. 

The problem comes however, when I attempt to create the nodes using the bolt driver with Javascript. 
Initially I had it setup so that the nodes were created in a transaction, which I have since changed to be outside a transaction to test. Nodes are commited/queries run with nodes being created but not attached. 

I have tested with timestamps before the latest node and after, neither condition makes a difference. 

The query used in both instances (Copy pasted from JS source into console and parameters substituted for actual usable values is:
```
match(m:Machine {serial:"123456"})<-[:owns]-(:HostNode {name:"Sample"}) create (f:Fault {dateOpened:1511883400000, dateClosed:1511883600000, description:"Dummy Fault Testing Feature"})-[:on]->(m) return f
```

I hope I'm simply missing something in the documentation or doing something rather stupid with my query. Any help with this would be greatly appreciated.

Thanks
-Andrew

**Comment by ikwattro** [comment]
Well, the neo4j browser uses javascript to connect to neo4j with bolt. Can you paste your javascript code in full. Thanks.

**Comment by bachmanm** [comment]
Your config is correct and our unit tests verify that the Framework and TimeTree work correctly. This is gonna sound silly, but can you try this please? Replace `"` in your query with a single quote (`'`)? Then let us know if it works please (don't ask me why)

**Comment by valandir** [comment]
I suspected the browser was made in such a way - hence my confusion...

Full JS code for the relevant section is as follows  (obviously minor changes ie passwords etc.):
```
  addFault(machineSerial: string, faultText: string, dateStart: number, dateEnd: number, feature?: string) {      
      // Open a neo4j Session.
      // Open a session transaction.
      const driver = neo4j.driver('bolt://localhost', neo4j.auth.basic('user', 'password'));
      const session = driver.session();

      let query: string;

          query = 'match(m:Machine {serial:$serial})<-[:owns]-(:HostNode {name:\'Sample\'}) ' +
              'create (f:Fault {dateOpened:$dateStart, dateClosed:$dateEnd, description:$faultDescription})-[:on]->(m) return f';
          console.log(query);
          session.run(query, {serial: machineSerial, dateStart: toNumber(dateStart), dateEnd: toNumber(dateEnd), faultDescription: faultText})
          .then(result => {
              console.log('Query Run');
              console.log(result);
              session.close();
          });
}
```
The variables are all passed into the function, and the feature variable is not used at current.

I've just adjusted the above code to use `'` rather than `"`. Unfortunately it did not add to the timetree attachement. The node has been added correctly and the `:on` relationship is created correctly.

I'm still hoping for my own stupidity at this point...

Thanks
-Andrew

**Comment by bachmanm** [comment]
Well I pushed the test. Find a difference between your code and the test code :) I don't see it

**Comment by valandir** [comment]
Thanks for that.

For info I've resolved the issue just now - turns out I hadn't read the documentation correctly. Where in the parameters section for the `session.run(...)` statement I should have cast the timestamps into integers as recognised by the neo4j JS driver. As standard without that call the driver treats it as a float value, which I am then guessing the timetree does not like as a timestamp and so didn't do the auto-attachment.

Resolved code follows:
```
  addFault(machineSerial: string, faultText: string, dateStart: number, dateEnd: number, feature?: string) {      
      // Open a neo4j Session.
      // Open a session transaction.
      const driver = neo4j.driver('bolt://localhost', neo4j.auth.basic('user', 'password'));
      const session = driver.session();

      let query: string;

          query = 'match(m:Machine {serial:$serial})<-[:owns]-(:HostNode {name:\'Sample\'}) ' +
              'create (f:Fault {dateOpened:$dateStart, dateClosed:$dateEnd, description:$faultDescription})-[:on]->(m) return f';
          console.log(query);
          session.run(query, {serial: machineSerial, dateStart: int(dateStart), dateEnd: int(dateEnd), faultDescription: faultText})
          .then(result => {
              console.log('Query Run');
              console.log(result);
              session.close();
          });
}
```
Hopefully this information will help someone else out in the future too!

Thanks for all the help and apologies for not realising my types error before posting!

-Andrew

**Comment by bachmanm** [comment]
Cool, thanks!!
