### ISSUE TITLE
ga.timetree.events.range() returns nodes for timeframes where there aren't any nodes attached to the tree

### ISSUE THREAD

**Issue by maxthemillion** [graphaware/neo4j-timetree#74]
I just encountered an issue using 
`CALL ga.timetree.events.range()`

When querying the timetree for a set of events in a specific timeframe like so:

`CALL ga.timetree.events.range({
start: apoc.date.parse('2016-01-01', 'ms', 'yyyy-MM-dd'), 
end: apoc.date.parse('2016-01-01', 'ms', 'yyyy-MM-dd'), 
direction: 'INCOMING'}) 
YIELD node 
RETURN COUNT(node)`

The query would return a high number of nodes (12998 in my case), when there is no node attached to the timetree for the specified date range.

For the query above, the corresponding ga.timeframe.events.single() call returns 0:

`CALL ga.timetree.events.single({
time: apoc.date.parse('2016-01-01', 'ms', 'yyyy-MM-dd'), 
direction: 'INCOMING'}) 
YIELD node 
RETURN COUNT(node) `

Also when querying the whole January 2016 like so:
`CALL ga.timetree.events.range({
start: apoc.date.parse('2016-01-01', 'ms', 'yyyy-MM-dd'), 
end: apoc.date.parse('2016-02-01', 'ms', 'yyyy-MM-dd'), 
direction: 'INCOMING'}) 
YIELD node 
RETURN COUNT(node)`

It returns a number of 12 nodes, which corresponds to the real number.

Is this intended behavior? If so, what is the result of the range query when it doesn't hit attached nodes in the specified timeframe? I couldn't find a corresponding number of nodes in the network. I would expect the query to return 0 in this case.

**Comment by bachmanm** [comment]
any chance you could provide a failing test case, or at least a database where this behaviour occurs? Thanks

**Comment by maxthemillion** [comment]
Sorry for my late reply. I didn't have the time to further elaborate on this one. Unfortunately, I am not very skilled in writing test cases. I set up a new database and the behavior did not occur again so far. If I encounter it again, I will do my best to provide some more information.
