### ISSUE TITLE
neo4j-timetree does not work with neo4j version 3.2.3

### ISSUE THREAD

**Issue by KrishnanSrinivasan** [graphaware/neo4j-timetree#76]
Hi, I'm trying Neo4j 3.2.3 Enterprise on my mac for a while now, extracted from neo4j-enterprise-3.2.3-unix.tar.gz. I wanted to use ga.timetree procedures in my cypher queries.

I pasted (graphaware-timetree-3.3.3.52.27.jar
graphaware-server-enterprise-all-3.3.3.52.jar) onto the plugins folder. And have the following entry in the neo4j.conf

dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware
dbms.security.procedures.unrestricted=ga.timetree.*

when I have the framework jar in the plugins folder the server won't start. I see the following error:
ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@34b81274' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.configuration.Settings.setting(Ljava/lang/String;Ljava/util/function/Function;Ljava/lang/String;)Lorg/neo4j/graphdb/config/Setting;".

I tried with the older versions 3.2.1.x and 3.2.5.x. I see the same error. 
if I comment the line 
dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware
or
If I delete the framework jar, the server starts, but the call to ga.timetree.single() reports a class not found error.

Here is the dump of the plugins folder:
ga-neo4j-ee>ls -u plugins/
apoc-3.2.3.5-all.jar				
graphaware-timetree-3.3.3.52.27.jar
graphaware-server-enterprise-all-3.3.3.52.jar

Could anyone please point out what the issue could be and how to resolve?

Thanks!
Krishnan.

**Comment by ikwattro** [comment]
You don't have any configuration specific to the timetree ? 

Like mentioned in the docs for eg ?

```
com.graphaware.runtime.enabled=true

# A Runtime module that takes care of attaching the events like this (TT is the ID of the module)
com.graphaware.module.TT.1=com.graphaware.module.timetree.module.TimeTreeModuleBootstrapper

# autoAttach must be set to true
com.graphaware.module.TT.autoAttach=true

# Optionally, nodes which represent events and should be attached automatically have to be defined (defaults to nodes with label Event)
com.graphaware.module.TT.event=hasLabel('Email')

# Optionally, a property on the event nodes that represents the the time (long) at which the event took place must be specified (defaults to "timestamp")
com.graphaware.module.TT.timestamp=time

# Optionally, a property on the event nodes that represents the node ID (long) of the root node for the tree, to which the event should be attached (defaults to "timeTreeRootId")
com.graphaware.module.TT.customTimeTreeRootProperty=rootId

# Optionally, a resolution can be specified (defaults to DAY)
com.graphaware.module.TT.resolution=HOUR

# Optionally, a time zone can be specified (defaults to UTC)
com.graphaware.module.TT.timezone=GMT+1

# Optionally, a relationship type with which the events will be attached to the tree can be specified (defaults to AT_TIME)
com.graphaware.module.TT.relationship=SENT_ON

# Optionally, a relationship direction (from the tree's point of view), with which the events will be attached to the tree can be specified (defaults to INCOMING)
com.graphaware.module.TT.direction=INCOMING

```

**Comment by KrishnanSrinivasan** [comment]
I have all required settings in the conf file.
[neo4j.log](https://github.com/graphaware/neo4j-timetree/files/1817834/neo4j.log)
[neo4j.conf.txt](https://github.com/graphaware/neo4j-timetree/files/1817835/neo4j.conf.txt)
